travis:
  secure:
    BINSTAR_TOKEN: EXslpPQ/1ulIiefCSwa+SbNYGRgc0FrJSuXLp30mMwM4Az5XN4xRyrARTfneB3j3jtn1sqb0lNsk0ODUghR6QjJAOq80gPC19hiw1+6ZO0f5L8Jx35pGbRWWGn+KU6mz7B3bLG1kOqXL0uVsOco6Ybn4KxfIxRUvwt+6mM8RNGIGVwNYn44qo0bap586d6VR5y9pWuusQPWbIxtwgq/HS8GcY04fia0DArtxkVNZLbDXxhKBc1nu5738pijTJMSS07SppC8j93VjyJ3AgX7v234z8Jfpk2tj3d860Y1AuRANsFUzl42CVqorhb1uPZ/5hAofAqwemFPtH/m+v6S/jt8DUoaDQZxk/PvEp7gALzCfvisBiIo/iSpOMC1ig2qX8o+625rlfVPsanhaAYX15SghgsnI3IBwL44swK/F0ZOlKkuIeErfEpS0bur+QX8QVaCniQBa/xwBSZCCounduIAaimwMi9xy1xqH18tFoTuseMt5EL9oDtiRF1IjVp6CBa219/jjuRCRmh+GnGLjk75io7C8KKMIFbn2fYRN8c6FzfypGyGbguLTJldkASUuRlYFZQz/4OwXSD6sMVrGl1Hw1v7d0nDJTd11qNO2VPF1gx0S766h3QHgSA+fNw5O3JTi4PCiuGZ4wDqF4NT+kvLOr9/GhM0iLSyaHhhEn0w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
